### ISSUE TITLE
asclepios: BW_FRONTEND n'a pas vraiment de sens

### ISSUE THREAD

**Issue by lnussbaum** [lpouillo/execo-g5k-tools#9]
... puisque la plupart des frontales sont des VM.
à mon avis, le plus simple est d'enlever ce test.

par contre, BW_ONEONE est vraiment long. est-ce qu'on ne pourrait pas se contenter de mesurer le débit avec "quelques" autres machines, histoires de garder un temps en O(n), et pas en O(n^2) ?

**Comment by lpouillo** [comment]
ok pour virer BW_FRONTEND des tests par DEFAUT.
